name: Publish npm package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js and authenticate
      - name: Setup Node.js and npm auth
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@gim2510'
          token: ${{ secrets.TECHBRIDGEGROUP_ACCESS_TOKEN }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build package
      - name: Build package
        run: npm run build

      # Step 5: Optional debug npm auth
      - name: Debug npm auth
        run: npm whoami

      # Step 6: Publish
      - name: Publish package
        run: npm publish